AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the OC::Organizations::PasswordPolicy resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.entrypoint
      Runtime: nodejs12.x
      CodeUri: ./

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs12.x
      CodeUri: ./
